version: '2'

services:
  ethminer:
    build:
      context: .
      args:
        REVISION: $REVISION
        ETHMINER_VERSION: $ETHMINER_VERSION
        CUDA_VERSION: $CUDA_VERSION
    image: chaznet/eth-cuda-miner:${CUDA_VERSION}-${ETHMINER_VERSION}-${REVISION}
